spring.application.name=jobPortal
spring.dataSource.url=jdbc:mysql://localhost:3306/jobportal
spring.datasource.username=root
spring.datasource.password=code@142005

logging.level.org.springframework.security=DEBUG
logging.level.org.thymeleaf=DEBUG

server.port=8080




